### ISSUE TITLE
EIP-999 msg.sender to get related token

### ISSUE THREAD

**Issue by naumenkogs** [Finhaven/EIPs#4]
> a Validator cannot rely on msg.sender to determine the token that it's about.

@expede Why so?

Do you want to make Validator.check() be runnable without actual transfer (probably you made it public for the same reason)?

**Comment by naumenkogs** [comment]
Now I see that you want to introduce check without transferring in token as a private function:

 `    function validate(
        address _from,
        address _to,
        uint256 _amount
    ) private returns (uint8 resultCode) {
        return validator.check(this, _from, _to, _amount);
    }
`

It feels contradictory to my prior assumption:
> make Validator.check() be runnable without actual transfer

**Comment by expede** [comment]
> a Validator cannot rely on msg.sender to determine the token that it's about.

Validators can be managed by several parties (ex. Finhaven, Equifax, the SEC, and so on). They may need to check each other's responses (ex. to pass an SEC audit you need an on-chain Equifax check). They also may want to update their internal caches if checks include a fee. There could be other cases as well. Since it's not always originating from a transfer, nor even from the token, and can delegate requests to other Validators, we need to pass the address of the token that we're talking about.

Here's a somewhat contrived diagram (with a typo) of the kind of system: https://github.com/Finhaven/ValidatedToken#example

Does that make sense? I could be misunderstanding some part of how Ethereum works.

---

> Do you want to make Validator.check() be runnable without actual transfer (probably you made it public for the same reason)?

Yes, that's right: I want to be able to do a few things:
* Check if a transfer is okay at all
* Check if it's okay for someone else to transfer (ex I'm doing this on their behalf)
* See if I can request a payment from someone (I'm the `_to`)
* Have Validators call other Validators (ex. lists maintained by different companies or agencies)

---

> It feels contradictory to my prior assumption:

>  > make Validator.check() be runnable without actual transfer

Ah, I see how this could be made clearer in comments/docs. The private `validate` functions are just helpers to avoid needing the `this` everywhere you call out to the external `Validator`. They're in the reference token just to demonstrate how to write a convenience function / maybe we provide a library.

**Comment by naumenkogs** [comment]
> Validators can be managed by several parties (ex. Finhaven, Equifax, the SEC, and so on)

You're right, I think it is clear from the EIP, I don't know why I was confused.
The diagram looks good.
